# Generated by Django 3.0.6 on 2024-11-05 10:51

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('image', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, default=list, size=None)),
                ('is_archived', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='posts.PostCategory')),
                ('comments_users_list', models.ManyToManyField(blank=True, related_name='post_comments_users', to=settings.AUTH_USER_MODEL)),
                ('iu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postdetails_iu', to='adminapp.IUMaster')),
                ('likes_users_list', models.ManyToManyField(blank=True, related_name='post_liked_users', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_publisher_id', to=settings.AUTH_USER_MODEL)),
                ('shared_users_list', models.ManyToManyField(blank=True, related_name='post_shared_users', to=settings.AUTH_USER_MODEL)),
                ('viewed_users_list', models.ManyToManyField(blank=True, related_name='post_viewed_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_details',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('sub_comment', models.BooleanField(default=False)),
                ('list_tag_user', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_removed_comment', models.BooleanField(default=False)),
                ('timestamp', models.IntegerField()),
                ('iu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_iu', to='adminapp.IUMaster')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comments_id', to='posts.Comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_post_id', to='posts.PostDetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
    ]
