# Generated by Django 3.0.6 on 2024-11-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comments_postdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdetails',
            old_name='status',
            new_name='post_status',
        ),
    ]
