# Generated by Django 3.0.6 on 2024-11-08 13:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20241108_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='list_tag_user',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
