# Generated by Django 3.0.6 on 2024-10-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('users', '0002_auto_20241029_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='iu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomUser_iu_id', to='adminapp.IUMaster'),
        ),
        migrations.AlterField(
            model_name='userpersonalprofile',
            name='iu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_personal_profile_iu', to='adminapp.IUMaster'),
        ),
    ]
