# Generated by Django 3.0.6 on 2024-10-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('users', '0004_auto_20241029_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='iu_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CustomUser_iu_id', to='adminapp.IUMaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rolemapping',
            name='iu_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.IUMaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rolemaster',
            name='iu_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.IUMaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpersonalprofile',
            name='iu_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_personal_profile_iu', to='adminapp.IUMaster'),
            preserve_default=False,
        ),
    ]
