# Generated by Django 3.0.6 on 2024-11-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_publisherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedProfiles',
            fields=[
                ('publisherprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.PublisherProfile')),
            ],
            options={
                'db_table': 'approved_profiles',
                'ordering': ['created_at'],
            },
            bases=('users.publisherprofile',),
        ),
    ]
