# Generated by Django 3.0.6 on 2024-11-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_approvedprofiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovedProfiles',
        ),
    ]
