# Generated by Django 3.0.6 on 2024-11-08 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('event_date', models.DateTimeField()),
                ('event_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('event_member_limit', models.IntegerField()),
                ('refund_applicable', models.BooleanField(default=False)),
                ('payment_needed', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('event_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer_id', to=settings.AUTH_USER_MODEL)),
                ('iu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventdetails_iu', to='adminapp.IUMaster')),
            ],
            options={
                'db_table': 'event_details',
                'ordering': ['created_at'],
            },
        ),
    ]
