# Generated by Django 3.0.6 on 2024-11-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='event_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
