# Generated by Django 3.0.6 on 2024-11-11 10:01

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20241108_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBookingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('event_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('no_of_tickets', models.IntegerField()),
                ('payment_status', models.CharField(default='unpaid', max_length=20)),
                ('booking_status', models.CharField(default='confirmed', max_length=20)),
                ('cancellation_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('refund_status', models.CharField(default='pending', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_id', to='events.EventDetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_booking_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_booking_details',
                'ordering': ['created_at'],
            },
        ),
    ]
