# Generated by Django 3.0.6 on 2024-11-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventbookingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbookingdetails',
            name='no_of_tickets',
            field=models.IntegerField(default=1),
        ),
    ]
