# Generated by Django 3.0.6 on 2024-11-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('events', '0005_auto_20241111_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbookingdetails',
            name='iu_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventbookingdetails_iu', to='adminapp.IUMaster'),
            preserve_default=False,
        ),
    ]
