# Generated by Django 3.0.6 on 2024-11-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventbookingdetails_iu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbookingdetails',
            name='payment_status',
        ),
    ]
