# Generated by Django 3.0.6 on 2024-11-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_eventbookingdetails_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbookingdetails',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
