# Generated by Django 3.0.6 on 2024-11-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventbookingdetails_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbookingdetails',
            name='no_of_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
