# Generated by Django 3.0.6 on 2024-11-25 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_auto_20241118_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
