# Generated by Django 3.0.6 on 2024-11-26 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('events', '0011_auto_20241126_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkdetails',
            name='iu_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_iu', to='adminapp.IUMaster'),
            preserve_default=False,
        ),
    ]
