# Generated by Django 3.0.6 on 2024-11-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_bookmarkdetails_iu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='inclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
