# Generated by Django 3.0.6 on 2024-12-03 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0013_auto_20241126_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBookmarkDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'event_bookmark_details',
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameField(
            model_name='eventdetails',
            old_name='is_archived',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='eventdetails',
            old_name='refund_applicable',
            new_name='is_refund_applicable',
        ),
        migrations.AddField(
            model_name='eventbookingdetails',
            name='cancelled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='eventbookingdetails',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='rejected_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='BookmarkDetails',
        ),
        migrations.AddField(
            model_name='eventbookmarkdetails',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_event', to='events.EventDetails'),
        ),
        migrations.AddField(
            model_name='eventbookmarkdetails',
            name='iu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_iu', to='adminapp.IUMaster'),
        ),
        migrations.AddField(
            model_name='eventbookmarkdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
