# Generated by Django 3.0.6 on 2024-11-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False)),
                ('web', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('iu_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eventmaster_iu_id', to='adminapp.IUMaster')),
            ],
            options={
                'db_table': 'event_master',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('iu_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='templatemaster_iu_id', to='adminapp.IUMaster')),
            ],
            options={
                'db_table': 'template_master',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email_message', models.TextField(blank=True, null=True)),
                ('sms_message', models.TextField(blank=True, null=True)),
                ('web_message', models.TextField(blank=True, null=True)),
                ('redirect_link', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_id', to='notification.EventMaster')),
                ('iu_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_iu_id', to='adminapp.IUMaster')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='template_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eventmaster_template', to='notification.TemplateMaster'),
        ),
    ]
