# Generated by Django 3.0.6 on 2024-11-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20241118_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatemaster',
            name='iu_id',
        ),
    ]
